### ISSUE TITLE
deprecated gulp scripts causing tests to fail

### ISSUE THREAD

**Issue by stchang** [vishesh/racketscript#145]
Here is an example error
```
TEST (1/106) => racket-core/list.rkt assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/home/stchang/racketscript-stchang/tests/js-build/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/home/stchang/racketscript-stchang/tests/js-build/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/home/stchang/racketscript-stchang/tests/js-build/gulpfile.js:15:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

Need to upgrade to gulp v4+

**Comment by stchang** [comment]
See more info here:
- https://github.com/gulpjs/undertaker/issues/54
- [how to upgrade to gulp 4](https://www.liquidlight.co.uk/blog/how-do-i-update-to-gulp-4/)
- https://fettblog.eu/gulp-4-parallel-and-series/

**Comment by vishesh** [comment]
A quick way to unblock yourself quickly with this is to force NPM to use older Gulp. I've some patches the `issue-143` branch. 

https://github.com/vishesh/racketscript/compare/master...task/issue-143

**Comment by stchang** [comment]
I think I managed to fix the gulp scripts to use v4. Is it better to use the old version or to update the scripts?

**Comment by vishesh** [comment]
Oh that's great. I think better to use v4.

I would also suggest updating `package.json` like here (https://github.com/vishesh/racketscript/commit/8c627bfc656dce3b6efd257bb0510fd57bc5116e#diff-f9624b01fe9c93281996c5aae44efa4aL18) which will keep the Gulp locked to specific major version series, so that it doesn't break next time Gulp updates their API.

**Comment by stchang** [comment]
> I would also suggest updating package.json like here

good idea. I will submit a pull request once I confirm the tests are passing.

**Comment by stchang** [comment]
The build still didnt run, for some reason.

**Comment by vishesh** [comment]
I just did a reset on Travis settings everywhere. Seems to have fixed it based on a test PR. I've also triggered a build a master.
