### ISSUE TITLE
`time` can't be used properly?

### ISSUE THREAD

**Issue by shriram** [vishesh/racketscript#24]
```
#lang racket

(define (gen n)
  (if (> n 0)
      (cons n (gen (sub1 n)))
      empty))

(define ls (gen 10000))

(time (length ls))
```

This program runs fine in DrRacket. But here it produces the error

```
Console Log: 
[error] TypeError: M0.time_apply is not a function
    at eval (http://rapture.twistedplane.com:8080/modules/index_inline_script_1.js:14:26)
    at Object.exports.call-with-values (http://rapture.twistedplane.com:8080/runtime/kernel.js:25:18)
  ...
```

Note that writing `time` on its own produces an error that suggests `time` is indeed defined.

**Comment by vishesh** [comment]
Thanks for trying RacketScript and reporting this issue. `time` expands to time-apply which is actually not defined in our kernel right now, but will definitely add it soon (for both NodeJs and Browser).

And yes, it should have complained right away that its not defined, rather than waiting for JS to apply an undefined value ! :)
