### ISSUE TITLE
lazy lang not found

### ISSUE THREAD

**Issue by shriram** [vishesh/racketscript#27]
```
#lang lazy

(define (odd? n)
  (if (zero? n) false (even? (sub1 n))))

(define (even? n)
  (if (zero? n) true (odd? (sub1 n))))

(odd? 100)
```

produces

```
Console Log: 
[error] Error: File not found 'http://rapture.twistedplane.com:8080/links/lazy/lazy.rkt.js'
Specified as ../links/lazy/lazy.rkt.js.
Normalizes to ../links/lazy/lazy.rkt.js
locate resolved against base 'http://rapture.twistedplane.com:8080/modules/index.html'

    at InternalLoader.handleCodeUnitLoadError (https://google.github.io/traceur-compiler/bin/BrowserSystem.js:33360:40)
    at https://google.github.io/traceur-compiler/bin/BrowserSystem.js:33222:20 
```

**Comment by stchang** [comment]
Yes, the unsupported parts of Racket need to produce better errors. We're working on this.
