### ISSUE TITLE
call/cc does not work

### ISSUE THREAD

**Issue by shriram** [vishesh/racketscript#29]
`(call/cc 3)` produces
```
Console Log: 
[error] TypeError: M0.call_by_cc is not a function
    at eval (http://rapture.twistedplane.com:8080/modules/index_inline_script_1.js:6:15)
    at Object.exports.call-with-values (http://rapture.twistedplane.com:8080/runtime/kernel.js:25:18)
blah
```

This isn't Racket.

**Comment by stchang** [comment]
Yes, call/cc is currently unsupported. It's definitely not Racket and we need to be clear about this.

**Comment by shriram** [comment]
> It's definitely not Racket and we need to be clear about this.

It's called _Racket_ Script… You don't think people might think otherwise?

**Comment by shriram** [comment]
PS: There's a reason why Whalesong did not use a name like "<something>Racket<something>", even though Whalesong actually implements arithmetic, continuations, etc. quite well.
