### ISSUE TITLE
Simple (factorial) Typed/Racket program fails

### ISSUE THREAD

**Issue by jsmaniac** [vishesh/racketscript#47]
I tried the following Typed/Racket program on http://rapture.twistedplane.com:8080/.

```
#lang typed/racket/base

(define (factorial [n : Integer])
  (let loop : Integer ([n : Integer n]
             [a : Integer 1])
    (if (zero? n)
        a
        (loop (sub1 n) (* n a)))))

(displayln (factorial 7))
```

I get the following error:

```
Console Log: 
[error] TypeError: M0.variable_reference__gt_module_source_by_submod is not a function
    at eval (http://rapture.twistedplane.com:8080/modules/index_inline_script_1.js:5:40)
    at Object.getAnonymousModule (https://google.github.io/traceur-compiler/bin/BrowserSystem.js:358:25)
    at eval (http://rapture.twistedplane.com:8080/modules/index_inline_script_1.js:1:29)
    at eval (<anonymous>)
    at LoaderCompiler.evaluateCodeUnit (https://google.github.io/traceur-compiler/bin/BrowserSystem.js:32970:38)
    at EvalCodeUnit.evaluate (https://google.github.io/traceur-compiler/bin/BrowserSystem.js:33130:36)
    at InternalLoader.evaluate (https://google.github.io/traceur-compiler/bin/BrowserSystem.js:33432:31)
    at InternalLoader.handleCodeUnitLoaded (https://google.github.io/traceur-compiler/bin/BrowserSystem.js:33345:18)
    at https://google.github.io/traceur-compiler/bin/BrowserSystem.js:33216:18 
```

The produced JS code (in the lower left pane) is:
```
import * as $rjs_core from '../runtime/core.js';
import * as M0 from "../runtime/kernel.rkt.js";
var blame1 = M0.module_name_fixup(M0.variable_reference__gt_module_source_by_submod(M0.__variable_reference), M0.list());
var factorial = function(n5) {
  var loop6 = function(_n74, _a85) {
    lambda_start3: while (true) {
      let n7 = _n74;
      let a8 = _a85;
      if (M0.zero_p(n7)) {
        return a8;
      } else {
        _n74 = M0.sub1(n7);
        _a85 = n7 * a8;
        continue lambda_start3;
      }
    }
  };
  return loop6(n5, 1);
};
M0.call_with_values(function() {
  return M0.displayln(factorial(7));
}, M0.print_values);
M0.rvoid();
```

**Comment by vishesh** [comment]
We have not looked into variable references and contracts yet. Once we get good support for basic Racket and harden it, we will follow up with contracts and start looking at Typed Racket.
