### ISSUE TITLE
Error: Cannot find module './dist/compiled.js'

### ISSUE THREAD

**Issue by amirouche** [vishesh/racketscript#83]
I just installed racketscript following the instruction from the README and I get the following errors:

```sh
$ nodejs js-build/bootstrap.js           

module.js:340
    throw err;
          ^
Error: Cannot find module './dist/compiled.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/amirouche/src/me/combinatorix/js-build/bootstrap.js:12:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by vishesh** [comment]
Looks like Gulp didn't compile `compiled.js`. Can you goto `js-build` directory and simply execute `gulp`? If it complains about not being able to find gulp, you can:

1. Try to execute `js-build/node_modules/.bin/gulp` which should be installed by npm invoked by RacketScript in your build dir.
2. Just install `gulp` globally using `npm install -g gulp`.

Hope this helps. If so please let me know what ended up being the problem.

**Comment by amirouche** [comment]
both commands fail to compile `compiled.js`.

**Comment by amirouche** [comment]
Ok I found out why. It's because my file was using `.scm` extension instead of `.rkt`.

Sorry for the noise.
